# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image to build the project
FROM node:20-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the source code
COPY src/ src/
COPY tsconfig.json ./

# Build the project
RUN npm run build

# Use a lightweight Node.js image for the runtime
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy built files from the builder stage
COPY --from=builder /app/build /app/build

# Set environment variables (replace with actual keys as needed)
ENV GLHF_API_KEY=your_api_key
ENV GROQ_API_KEY=your_api_key
ENV OPENAI_API_KEY=your_api_key
ENV OPENROUTER_API_KEY=your_api_key
ENV GITHUB_API_KEY=your_api_key
ENV DEEPSEEK_API_KEY=your_api_key
ENV GEMINI_API_KEY=your_api_key

# Set the entrypoint for the Docker container
ENTRYPOINT ["node", "/app/build/index.js"]
